In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [4]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data'
# creating data-frame df_ords
df_ords = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Prepared_Data/orders_wrangled_task4_04.csv', index_col = False)
# creating data-frae df_prods
df_prods = pd.read_csv(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Original_Data/products.csv', index_col = False)

In [6]:
# Step 1 Consistency data check on df_ords
df_ords.describe()

,Unnamed: 0,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710541e+06,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552705e+05,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710541e+06,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421082e+06,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [8]:
# Step 1 Consistency data check on df_prods
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [12]:
# data-frame df_ords contains a column "Unnamed:0" which could be dropped
df_ords.drop(columns=['Unnamed: 0'], inplace =True)

In [14]:
# Consistency data check on df_ords after dropping the column
df_ords.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [20]:
# Checking the accuracy of the columns in the df_ords dataframe.
# No unreasonable values were found. 
# All values in the columns appear to fall within an acceptable and interpretable
# range for their corresponding columns/variables.

In [16]:
# Step 3 - Check for mixed-type data in your df_ords data-frame.

In [38]:
# Step 4 Check for mixed type columns
for col in df_ords.columns.tolist():
  weird = (df_ords[[col]].map(type) != df_ords[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_ords[weird]) > 0:
    print (col)

In [24]:
# df-ords doesn't have mixed-type data so I will create a fake one to work with

In [28]:
# Creating a test data-frame
df_test=pd.DataFrame()

In [30]:
# Creating a mixed type column
df_test['mix']=['a', 'b', 1, True]

In [32]:
# Checking the test data-frame
df_test.head()

    mix
0     a
1     b
2     1
3  True

In [34]:
# Check for mixed type columns
for col in df_test.columns.tolist():
  weird = (df_test[[col]].map(type) != df_test[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_test[weird]) > 0:
    print (col)

mix

In [36]:
# Converting a column’s data type from numeric to string
df_test['mix'] = df_test['mix'].astype('str')

In [40]:
# Step 5 - Run a check for missing values in your df_ords data-frame
df_ords.isnull().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [42]:
# There are a total of 206209 missing values in the column days_since_prior_order. 
# An explanation for this quanitty of missing values could be customers' first orders don't have a value.
# However, we must keep this information instead of remove it.

In [44]:
# Step 6 - Address the missing values using an appropriate method.

In [46]:
# To determine what course of action to take regarding the missing values, we must separate the data from the original dataframe,
df_ords_nan = df_ords[df_ords['days_since_prior_order'].isnull() == True]

In [50]:
df_ords_nan

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
11,2168274,2,prior,1,2,11,NaN
26,1374495,3,prior,1,1,14,NaN
39,3343014,4,prior,1,6,11,NaN
45,2717275,5,prior,1,3,12,NaN
...,...,...,...,...,...,...,...
3420930,969311,206205,prior,1,4,12,NaN
3420934,3189322,206206,prior,1,3,18,NaN
3421002,2166133,206207,prior,1,6,19,NaN
3421019,2227043,206208,prior,1,1,15,NaN
3421069,3154581,206209,prior,1,3,11,NaN

In [54]:
# Now we must verify whether all 'order_number' values equal to 1 are missing values in the 'days_since_prior_order' column

In [56]:
# Filter the dataframe where 'order_number' equals 1\n
df_first_orders = df_ords_nan[df_ords_nan['order_number'] == '1']

In [58]:
# Check if all of these have missing values in 'days_since_prior_order'
df_first_orders_missing = df_first_orders['days_since_prior_order'].isna().all()

In [66]:
# Print the result
print("All first orders have missing 'days_since_prior_order':", df_first_orders_missing)

All first orders have missing 'days_since_prior_order': True

In [68]:
# We know for certain that every row with 'order_number' equal to 1 has a missing value in the'days_since_prior_order' column

In [70]:
# Address the missing values by creating a column that flags order numbers as either True/False depending on if the 'order_number' = 1\n",
df_ords['first_order'] = df_ords['days_since_prior_order'].isna()

In [72]:
df_ords

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order
0,2539329,1,prior,1,2,8,NaN,True
1,2398795,1,prior,2,3,7,15.0,False
2,473747,1,prior,3,3,12,21.0,False
3,2254736,1,prior,4,4,7,29.0,False
4,431534,1,prior,5,4,15,28.0,False
...,...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0,False
3421079,1854736,206209,prior,11,4,10,30.0,False
3421080,626363,206209,prior,12,1,12,18.0,False
3421081,2977660,206209,prior,13,1,12,7.0,False
3421082,272231,206209,train,14,6,14,30.0,False

In [74]:
# Check data-type of new column and update if necessary
df_ords['first_order'].dtype

dtype('bool')

In [76]:
# Re-check data to make sure totals are accurate
df_ords.isnull().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
first_order                    0
dtype: int64

In [78]:
# Missing values have been addressed appropriately, now the client can see why there are missing values in the 'order_number' column\n",
# Removing/filtering these values would've been incorrect because the missing data is quite valuable

In [80]:
# Step 7 - Run a check for duplicate values in your df_ords data

In [84]:
df_ords_dup = df_ords[df_ords.duplicated()]

In [86]:
df_ords_dup

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, first_order]
Index: []

In [88]:
# The dataframe created to check duplicates has returned empty, meaning there are no duplicates in the data set

In [94]:
# Step 8 - Running Consitency check on the data-frame df_prods
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [98]:
# Checking the result it is clear that the maximum value in the column 'prices' is unusually high '99999'
# The column 'product_id' has a maximum value of 49688, assuming the count of 49672 is correct (meaning
# there are 49672 unique products) there should be an error and/or duplicate values

In [104]:
# Check data-frame df_prods shape
df_prods.shape

(49693, 5)

In [106]:
# Finding missing values for data-frame df_prods
df_prods.isnull().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [108]:
# Creating a new Data-Frame containing only the missing values (condition isnull()=True)
df_nan=df_prods[df_prods['product_name'].isnull()==True]

In [110]:
# checking the new data-frame which contian the missing valuse
df_nan

       product_id product_name  aisle_id  department_id  prices
33             34          NaN       121             14    12.2
68             69          NaN        26              7    11.8
115           116          NaN        93              3    10.8
261           262          NaN       110             13    12.1
525           525          NaN       109             11     1.2
1511         1511          NaN        84             16    14.3
1780         1780          NaN       126             11    12.3
2240         2240          NaN        52              1    14.2
2586         2586          NaN       104             13    12.4
3159         3159          NaN       126             11    13.1
3230         3230          NaN       120             16    14.4
3736         3736          NaN        41              8    14.8
4283         4283          NaN        77              7    14.4
4790         4790          NaN        91             16    14.5
38187       38183          NaN        39             12    20.9
40444       40440          NaN       120             16    14.8

In [112]:
# Finding upper and lower outliers for data-frame df_prods
df_prods[(df_prods['prices'] > df_prods['prices'].mean() + 0.5 * df_prods['prices'].std()) |
                    (df_prods['prices'] < df_prods['prices'].mean() - 0.5 * df_prods['prices'].std())]

,product_id,product_name,aisle_id,department_id,prices
21554,21553,Lowfat 2% Milkfat Cottage Cheese,108,16,14900.0
33666,33664,2 % Reduced Fat Milk,84,16,99999.0

In [114]:
# Finding the median for data-frame df_prods
df_prods['prices'].median()

7.1

In [116]:
# Replacing the outliers (upper/lower) values with the median
df_prods = df_prods.replace({"prices": {14900.0: 7.1, 99999.0: 7.1}})

In [118]:
# checking the data-frame df_prods after replacing the outliers
df_prods.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      7.682245
std    14343.717401     38.316774       5.850282      4.200159
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000     25.000000

In [120]:
# The maximum value in the column 'prices' is now in a normal range.
# Previously, the mean was 9.99 and the standard deviation was 453.6 indicating extreme values.
# Two outliers (14900 and 99999) were identified and replaced with the median value of 7.1.
# After replacing the outliers, the mean decreased to 7.6.

In [124]:
# Creating a new data-frame without missing values
df_prods_clean = df_prods[df_prods['product_name'].isnull() == False]

In [128]:
# Check data-frame df_prods shape
df_prods_clean.shape

(49677, 5)

In [130]:
# looking for full duplicates in dataframe df_prods_clean:
df_dups = df_prods_clean[df_prods_clean.duplicated()]

In [132]:
# checking the df_dups data-frame
df_dups

,product_id,product_name,aisle_id,department_id,prices
462,462,Fiber 4g Gummy Dietary Supplement,70,11,4.8
18459,18458,Ranger IPA,27,5,9.2
26810,26808,Black House Coffee Roasty Stout Beer,27,5,13.4
35309,35306,Gluten Free Organic Peanut Butter & Chocolate ...,121,14,6.8
35495,35491,Adore Forever Body Wash,127,11,9.9

In [134]:
# Creating a new dta-frame that doesn't include diuplicates
df_prods_clean_no_dups = df_prods_clean.drop_duplicates()

In [136]:
# Checking the number of rows of the new data-fram after having removed the duplicates
df_prods_clean_no_dups.shape

(49672, 5)

In [138]:
# Step 9

In [140]:
# export data-frame free from duplicates as "products_checked_task4_05.csv"
df_prods_clean_no_dups.to_csv(os.path.join(path,'Prepared_Data','products_checked_task4_05.csv'))

In [142]:
# export data-frame free from duplicates as "products_checked_task4_05.csv"
df_ords.to_csv(os.path.join(path,'Prepared_Data','orders_checked_task4_05.csv'))