In [4]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [6]:
# create path
path='/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data'

In [14]:
# Importing ords_prods_merge
ords_prods_merge=pd.read_pickle(r'/home/haus/Exercise_4_Instacart_Basket_Analysis/02_Data/Prepared_Data/ords_prods_merge.pkl')

In [16]:
# Creating a subset of the data-frame ords_prods_merge
df_subset = ords_prods_merge[:1000000]

In [20]:
# Checking the subset shape
df_subset.shape

(1000000, 17)

In [22]:
# Define a function to sort products data-frame ords_prods_merge according to price
def price_label(row):
  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [26]:
# Apply the function
df_subset['price_range']=df_subset.apply(price_label, axis=1)

/tmp/ipykernel_44144/826718590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['price_range']=df_subset.apply(price_label, axis=1)

In [28]:
# Check the values in the new column (price_range) created after applying the function
df_subset['price_range'].value_counts(dropna=False)

price_range
Mid-range product    673340
Low-range product    314392
High range            12268
Name: count, dtype: int64

In [30]:
# Repeat previous exercise using If-Statements with the function loc() for data-frame "ords_prods_merge" part 1
ords_prods_merge.loc[ords_prods_merge['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [34]:
# Repeat previous exercise using If-Statements with the function loc() for data-frame "ords_prods_merge" part 2
ords_prods_merge.loc[(ords_prods_merge['prices'] <= 15) & (ords_prods_merge['prices']>5),'price_range_loc'] = 'Mid-range product'

In [36]:
# Repeat previous exercise using If-Statements with the function loc() for data-frame "ords_prods_merge" part 3
ords_prods_merge.loc[ords_prods_merge['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [42]:
# Check the values in the new column (price_range_loc) created after applying the function loc() to the entire data-frame
ords_prods_merge['price_range_loc'].value_counts(dropna=False)

price_range_loc
Mid-range product     21865987
Low-range product     10126321
High-range product      412551
Name: count, dtype: int64

In [52]:
# Check the columns in data-frame
print(ords_prods_merge.columns)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'first_order',
       'product_id', 'add_to_cart_order', 'reordered', 'Unnamed: 0_y',
       'product_name', 'aisle_id', 'department_id', 'prices', 'merge_info',
       'price_range_loc'],
      dtype='object')

In [68]:
# Check frequency of the “order_dow” column
ords_prods_merge['order_dow'].value_counts(dropna=False)

order_dow
0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: count, dtype: int64

In [112]:
# Create a new column in data-frame ords_prods_merge that summarizes how busy each day of the week is
result = []
for value in ords_prods_merge["order_dow"]:
  if value == 0:
    result.append("Top Busiest day")
  elif value == 1:
    result.append("Second Busiest day")    
  elif value == 6:
    result.append("third Least busy")
  elif value == 4:
    result.append("Least busy")    
  else:
    result.append("Regularly busy")

In [114]:
# Print the result
result

['Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'third Least busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Top Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Second Busiest day',
 'Second Busiest day',
 'Second Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 ...]

In [116]:
# Combining the result with the data-fram to create a new column
ords_prods_merge['busiest_day']=result

In [118]:
# Display the frequency of values in the 'busiest_day' column (including NaN values)
ords_prods_merge['busiest_day'].value_counts(dropna=False)

busiest_day
Regularly busy        12260155
Top Busiest day        6204182
Second Busiest day     5660230
third Least busy       4496490
Least busy             3783802
Name: count, dtype: int64

In [120]:
# Step 2 #2 Suppose your clients have changed their minds about the labels you created in
# your “busiest_day” column. Now, they want “Busiest day” to become “Busiest days” (plural).
# This label should correspond with the two busiest days of the week as opposed to the single busiest day.
# At the same time, they’d also like to know the two slowest days. Create a new column for this using a suitable method.

In [122]:
result2 = []
for value in ords_prods_merge["order_dow"]:
  if value == 0 or value == 1: 
    result2.append("Busiest days")
  elif value == 3 or value == 4:
    result2.append("Lowest Busy days")    
  else:
    result2.append("Regularly busy days")

In [124]:
#  Check the Length of result2
print(len(result2))

32404859

In [126]:
# Combining the result with the data-fram to create a new column
ords_prods_merge['Busiest_days']=result2

In [134]:
# Display the frequency of values in the 'Busiest_days' column
ords_prods_merge['Busiest_days'].value_counts(dropna=False)

Busiest_days
Regularly busy days    12916111
Busiest days           11864412
Lowest Busy days        7624336
Name: count, dtype: int64

In [130]:
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,merge_info,price_range_loc,busiest_day,Busiest_days
0,2539329,1,prior,1,2,8,NaN,True,196,1,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days
1,2539329,1,prior,1,2,8,NaN,True,14084,2,0,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy days
2,2539329,1,prior,1,2,8,NaN,True,12427,3,0,12427,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days
3,2539329,1,prior,1,2,8,NaN,True,26088,4,0,26089,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy days
4,2539329,1,prior,1,2,8,NaN,True,26405,5,0,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy days

In [132]:
ords_prods_merge.shape

(32404859, 20)

In [136]:
# Step 3 - the busiest_days value counts are much closer together than the busiest_day value counts
# because we are now grouping the days in groups of 2 or 3 days as opposed 1 or 5 days.

In [138]:
# Step 4 - identify the busiest hours of the day. Rather than by hour, they want periods of time labeled
# “Most orders,” “Average orders,” and “Fewest orders.”
# Create a new column containing these labels called “busiest_period_of_day"

In [140]:
# create list of hours sorted by value count
hours_sorted=ords_prods_merge['order_hour_of_day'].value_counts(dropna=False).index.to_numpy()

In [142]:
# Create an empty list and use a for-loop to populate it with busiest time of day labels
busiest_hour = [] # Initialize an empty list
for row in ords_prods_merge['order_hour_of_day']:  # Iterate over the column
    if row in hours_sorted[:8]:  # Check if the hour is in the first 8 hours
        busiest_hour.append("Most orders")  # Append "Most orders"
    elif row in hours_sorted[8:16]:  # Check if the hour is in the next 8 hours
        busiest_hour.append("Average orders")  # Append "Average orders"
    else:  # For all other hours
        busiest_hour.append("Fewest orders")  # Append "Fewest orders"

In [144]:
# create column in dataframe equal to busiest_hour
ords_prods_merge['busiest_period_of_day'] = busiest_hour

In [148]:
# Check the output
ords_prods_merge.shape

(32404859, 21)

In [150]:
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,...,Unnamed: 0_y,product_name,aisle_id,department_id,prices,merge_info,price_range_loc,busiest_day,Busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2539329,1,prior,1,2,8,NaN,True,14084,2,...,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
2,2539329,1,prior,1,2,8,NaN,True,12427,3,...,12427,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders
3,2539329,1,prior,1,2,8,NaN,True,26088,4,...,26089,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders
4,2539329,1,prior,1,2,8,NaN,True,26405,5,...,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders

In [154]:
# Step 5 - Print the frequency for the new column “busiest_period_of_day”
ords_prods_merge['busiest_period_of_day'].value_counts(dropna = False)

busiest_period_of_day
Most orders       21118071
Average orders     9997651
Fewest orders      1289137
Name: count, dtype: int64

In [158]:
# Display info about the rows and columns for data-frame ords_prods_merge
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 21 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
 7   first_order             bool
 8   product_id              int64
 9   add_to_cart_order       int64
 10  reordered               int64
 11  Unnamed: 0_y            int64
 12  product_name            object
 13  aisle_id                int64
 14  department_id           int64
 15  prices                  float64
 16  merge_info              category
 17  price_range_loc         object
 18  busiest_day             object
 19  Busiest_days            object
 20  busiest_period_of_day   object
dtypes: bool(1), category(1), float64(2), int64(11), object(6)
memory usage: 4.6+ GB

In [160]:
# Step 7 - Export your dataframe as a pickle file (since you added new columns) and store it correctly in your “Prepared Data” folder.
ords_prods_merge.to_pickle(os.path.join(path, 'Prepared_Data', 'orders_products_merged_derived.pkl'))

# Close